# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#
development:
  adapter: postgresql
  encoding: utf8
  database: whoami
  pool: 5
  username: whoami_user
  password: a
