# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
production: &production
  :url: <%= ENV["REDISTOGO_URL"] %>
  :timeout: 1

development:
  url: redis://localhost:6379/2

test:
  url: redis://localhost:6379/3
